spring:
  application:
    name: config-server
  profiles:
    active: native

#默认配置  
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config
          
  rabbitmq:
    host: 192.168.74.128
    port: 5672
    username: admin
    password: admin
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/MyzwzyzK/sp_repo/tree/master/sp-config
#          searchPaths: config
#          username: MrzwzyzK
#          password: YzZ28109785
    
server:
  port: 6001
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
